### PR TITLE
remove theta_out

### PR DESCRIPTION
**Pull request by aleksada**

### CODE REVIEW

**Comment by SAbdulah** [comment]
@aleksada, please remove `.Rproj.user` directory.

**Comment by SAbdulah** [comment]
please also remove `.Rhistory` and `.DS_store` use `git rm` if you still need them. @aleksada

**Comment by SAbdulah** [comment]
@aleksada, you have only removed a commented line. Is this what we need?

**Comment by aleksada** [comment]
It is not a commented line. It will be an executable line in the examples
Screen Shot 2020-08-31 at 10 41 13 AM

**Pull request merged**
