### PR TITLE
Yuxiao

### PR DESCRIPTION
**Pull request by aleksada**
I have merged Jian's code and add the test files as examples into new functions.

### CODE REVIEW

**Comment by SAbdulah** [comment]
I am trying to install the package with your changes

**Comment by SAbdulah** [comment]
I think based on @SamCao1991 changes `dmetric` is accepting string now. @aleksada, could you did this changes to your code?

**Comment by SAbdulah** [comment]
Do we need to call check_args in all examples, or it is called automatically? and if it is automatic, why we are calling assert again in the examples? @aleksada

**Comment by SAbdulah** [comment]
Installation works fine! @aleksada

**Comment by aleksada** [comment]
I think Jian has put the argument check functions into the associated main functions. So we do not need them in the examples,

**Comment by SAbdulah** [comment]
@aleksada, Could you please remove them from examples?

**Comment by aleksada** [comment]
@SAbdulah I do not use the argument check functions in the examples.

**Comment by SAbdulah** [comment]
okay, I will merge this now to go to the next step.

**Comment by SAbdulah** [comment]
@aleksada, please leave the merging to me since I am trying the package with the new changes before the merge.

**Comment by aleksada** [comment]
Sorry! I thought everyone had to click to merge.

**Pull request merged**
